"""Generate AI storytelling reports and PDF exports."""
from __future__ import annotations

import os
from io import BytesIO
import json
import datetime
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Dict, List

import pandas as pd
from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import LETTER


PURPLE = HexColor("#7C3AED")
PURPLE_LIGHT = HexColor("#EDE9FE")
TEAL = HexColor("#0D9488")
TEAL_LIGHT = HexColor("#CCFBF1")
DARK_BG = HexColor("#0B0D14")
CARD_BG = HexColor("#F8F7FF")
BORDER = HexColor("#E5E3F0")
TEXT_PRIMARY = HexColor("#1A1523")
TEXT_MUTED = HexColor("#6B6580")
GREEN = HexColor("#10B981")
AMBER = HexColor("#F59E0B")
RED = HexColor("#EF4444")


def _safe_json_loads(raw: str, fallback: Any) -> Any:
    try:
        return json.loads(raw)
    except Exception:
        return fallback


def _compute_data_quality(dataframe: pd.DataFrame) -> Dict[str, Any]:
    max_rows_raw = (os.getenv("REPORT_QUALITY_SAMPLE_ROWS") or "100000").strip()
    try:
        max_rows = max(1000, int(max_rows_raw))
    except ValueError:
        max_rows = 100000

    # Sample for very large datasets to keep report generation responsive.
    quality_df = dataframe if len(dataframe) <= max_rows else dataframe.sample(n=max_rows, random_state=42)

    total_cells = max(1, quality_df.shape[0] * max(1, quality_df.shape[1]))
    null_cells = int(quality_df.isna().sum().sum())
    null_pct = (null_cells / total_cells) * 100

    duplicate_pct = (quality_df.duplicated().sum() / max(1, len(quality_df))) * 100

    numeric_cols = quality_df.select_dtypes(include=["number"]).columns.tolist()
    outlier_count = 0
    numeric_count = 0
    for col in numeric_cols:
        series = pd.to_numeric(quality_df[col], errors="coerce").dropna()
        numeric_count += len(series)
        if series.empty:
            continue
        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)
        iqr = q3 - q1
        if iqr == 0:
            continue
        low = q1 - 1.5 * iqr
        high = q3 + 1.5 * iqr
        outlier_count += int(((series < low) | (series > high)).sum())

    outlier_rate = (outlier_count / max(1, numeric_count)) * 100
    completeness_score = max(0, min(100, int(round(100 - (null_pct * 0.6 + duplicate_pct * 0.25 + outlier_rate * 0.15)))))

    return {
        "null_percent": round(null_pct, 2),
        "duplicate_percent": round(duplicate_pct, 2),
        "outlier_rate": round(outlier_rate, 2),
        "completeness_score": completeness_score,
    }


def _draw_header(canv, doc, safe_name: str, today: str) -> None:
    width, height = LETTER
    canv.saveState()
    canv.setFillColor(PURPLE)
    canv.rect(0, height - 110, width, 110, stroke=0, fill=1)

    canv.setFillColor(white)
    canv.setFont("Helvetica-Bold", 22)
    canv.drawString(50, height - 45, "InsightFlow")

    canv.setFont("Helvetica", 11)
    canv.drawString(50, height - 68, "AI-Powered Data Analysis Report")

    canv.setFillColor(HexColor("#CCBBFF"))
    canv.setFont("Helvetica", 9)
    canv.drawString(50, height - 88, f"Generated by InsightFlow · {safe_name}")

    canv.setFillColor(white)
    canv.setFont("Helvetica", 9)
    canv.drawRightString(width - 50, height - 68, today)
    canv.restoreState()


def _draw_footer(canv, doc, safe_name: str, today: str) -> None:
    width, _ = LETTER
    canv.saveState()
    canv.setStrokeColor(PURPLE)
    canv.setLineWidth(1)
    canv.line(50, 40, width - 50, 40)

    canv.setFont("Helvetica", 8)
    canv.setFillColor(TEXT_MUTED)
    canv.drawString(50, 28, f"InsightFlow AI Report · {safe_name}")
    canv.drawCentredString(width / 2, 28, f"Generated {today}")
    canv.drawRightString(width - 50, 28, f"Page {canv.getPageNumber()}")
    canv.restoreState()


def _section_title(title: str) -> List[Any]:
    from reportlab.platypus import Spacer, Table, TableStyle

    data = [["", title]]
    t = Table(data, colWidths=[6, 480])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), PURPLE),
        ("TEXTCOLOR", (1, 0), (1, 0), TEXT_PRIMARY),
        ("FONTNAME", (1, 0), (1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (1, 0), (1, 0), 13),
        ("LEFTPADDING", (1, 0), (1, 0), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return [t, Spacer(1, 10)]


def _build_quality_card(data_quality: Dict[str, Any], style_normal, style_muted):
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Table, TableStyle

    score = float(data_quality.get("completeness_score", 0) or 0)
    score_color = GREEN if score >= 75 else (AMBER if score >= 50 else RED)
    grade = (
        "Excellent" if score >= 90 else
        "Good" if score >= 75 else
        "Fair" if score >= 60 else
        "Poor" if score >= 40 else
        "Critical"
    )

    score_style = ParagraphStyle(
        "score_style",
        parent=style_normal,
        fontName="Helvetica-Bold",
        fontSize=40,
        leading=42,
        textColor=score_color,
        spaceAfter=4,
    )
    score_suffix = ParagraphStyle(
        "score_suffix",
        parent=style_normal,
        fontName="Helvetica",
        fontSize=16,
        leading=20,
        textColor=TEXT_MUTED,
    )
    grade_style = ParagraphStyle(
        "grade_style",
        parent=style_muted,
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=TEXT_PRIMARY,
    )

    left_block = [
        [
            Paragraph(f"{int(round(score))}", score_style),
            Paragraph("/ 100", score_suffix),
        ],
        [Paragraph(grade, grade_style), ""],
    ]
    left_table = Table(left_block, colWidths=[70, 60])
    left_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("SPAN", (0, 1), (1, 1)),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))

    def _pct(label: str, value: Any, color) -> List[Any]:
        val = float(value or 0)
        return [
            Paragraph(label, style_muted),
            Paragraph(
                f'<font color="{color.hexval()}"><b>{val:.2f}%</b></font>',
                style_normal,
            ),
        ]

    right_rows = [
        _pct("Missing Values", data_quality.get("null_percent", 0), RED),
        _pct("Duplicates", data_quality.get("duplicate_percent", 0), AMBER),
        _pct("Outlier Rate", data_quality.get("outlier_rate", 0), TEAL),
    ]
    right_table = Table(right_rows, colWidths=[130, 90], rowHeights=[24, 24, 24])
    right_table.setStyle(TableStyle([
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW", (0, 0), (-1, 1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))

    outer = Table([[left_table, right_table]], colWidths=[190, 300])
    outer.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 1, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    return outer


def _build_anomaly_table(anomalies: List[Dict[str, Any]]):
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

    body_style = ParagraphStyle(
        "anomaly_body",
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=TEXT_PRIMARY,
    )

    table_rows = [["Column", "Value", "Severity", "Explanation"]]
    for item in anomalies[:10]:
        sev = str(item.get("severity", "low")).lower().strip()
        table_rows.append([
            str(item.get("column", item.get("field", "-"))),
            str(item.get("value", "-")),
            sev.title(),
            Paragraph(str(item.get("explanation", item.get("reason", ""))), body_style),
        ])

    t = Table(table_rows, colWidths=[70, 60, 55, 240], repeatRows=1)
    styles = [
        ("BACKGROUND", (0, 0), (-1, 0), PURPLE),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_PRIMARY),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]

    for row_idx in range(1, len(table_rows)):
        bg = CARD_BG if row_idx % 2 == 0 else white
        styles.append(("BACKGROUND", (0, row_idx), (-1, row_idx), bg))
        sev = str(table_rows[row_idx][2]).lower()
        if sev == "high":
            styles.extend([
                ("BACKGROUND", (2, row_idx), (2, row_idx), HexColor("#FECACA")),
                ("TEXTCOLOR", (2, row_idx), (2, row_idx), RED),
            ])
        elif sev == "medium":
            styles.extend([
                ("BACKGROUND", (2, row_idx), (2, row_idx), HexColor("#FEF3C7")),
                ("TEXTCOLOR", (2, row_idx), (2, row_idx), AMBER),
            ])
        else:
            styles.extend([
                ("BACKGROUND", (2, row_idx), (2, row_idx), HexColor("#F3F4F6")),
                ("TEXTCOLOR", (2, row_idx), (2, row_idx), TEXT_MUTED),
            ])

    t.setStyle(TableStyle(styles))

    if len(anomalies) > 10:
        remaining = len(anomalies) - 10
        note_style = ParagraphStyle(
            "anomaly_note",
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=12,
            textColor=TEXT_MUTED,
        )
        note = Paragraph(
            f"+ {remaining} more anomalies - run full analysis for complete list",
            note_style,
        )
        return Table([[t], [Spacer(1, 6)], [note]], colWidths=[425])
    return t


def _build_chart_cards(chart_recommendations: List[Dict[str, Any]], style_muted):
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Table, TableStyle

    title_style = ParagraphStyle(
        "chart_card_title",
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=PURPLE,
    )
    body_style = ParagraphStyle(
        "chart_card_body",
        parent=style_muted,
        fontSize=9,
        leading=12,
        textColor=TEXT_PRIMARY,
    )

    cards = []
    for rec in chart_recommendations[:9]:
        chart_type = str(rec.get("chart_type", "Chart")).replace("_", " ").title()
        x_col = str(rec.get("x", "-"))
        y_col = str(rec.get("y", "-"))
        reason = str(rec.get("reason", "No rationale provided."))
        card = Paragraph(
            f"<b>{chart_type}</b><br/><font color='{TEXT_MUTED.hexval()}'>x: {x_col}</font>"
            f"<br/><font color='{TEXT_MUTED.hexval()}'>y: {y_col}</font><br/>{reason}",
            body_style,
        )
        cards.append(card)

    while len(cards) % 3 != 0:
        cards.append(Paragraph("", title_style))

    rows = [cards[i:i + 3] for i in range(0, len(cards), 3)]
    table = Table(rows, colWidths=[163, 163, 163], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 0.8, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.6, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table


def _build_forecast_section(forecasts: List[Dict[str, Any]], style_normal, style_muted):
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Table, TableStyle

    rows = []
    for item in forecasts[:8]:
        col = str(item.get("column", "Series"))
        date_range = str(item.get("date_range", "Date range unavailable"))
        method = str(item.get("method", "Auto"))
        trend = str(item.get("trend", "stable")).lower()
        pct = float(item.get("pct_change", 0) or 0)
        interpretation = str(item.get("llm_interpretation", item.get("summary", "")))

        if trend == "up":
            badge_bg = HexColor("#D1FAE5")
            badge_fg = GREEN
            trend_label = "Up"
        elif trend == "down":
            badge_bg = HexColor("#FEE2E2")
            badge_fg = RED
            trend_label = "Down"
        else:
            badge_bg = HexColor("#F3F4F6")
            badge_fg = TEXT_MUTED
            trend_label = "Stable"

        left = Paragraph(
            f"<b>{col}</b><br/><font color='{TEXT_MUTED.hexval()}'>{date_range}</font>"
            f"<br/><font color='{TEXT_MUTED.hexval()}'>Method: {method}</font>",
            style_normal,
        )
        right = Paragraph(
            f"<font backcolor='{badge_bg.hexval()}' color='{badge_fg.hexval()}'><b> {trend_label} </b></font>"
            f" <font color='{badge_fg.hexval()}'><b>{pct:+.2f}%</b></font><br/>{interpretation}",
            ParagraphStyle(
                "forecast_right",
                parent=style_muted,
                fontSize=9,
                leading=12,
                textColor=TEXT_PRIMARY,
            ),
        )
        rows.append([left, right])

    if not rows:
        return Paragraph("No forecast items available.", style_muted)

    t = Table(rows, colWidths=[210, 280])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 1, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def _build_text_analysis_section(columns: List[Dict[str, Any]], style_normal, style_muted):
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

    blocks: List[Any] = []
    heading_style = ParagraphStyle(
        "text_column_heading",
        parent=style_normal,
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=TEXT_PRIMARY,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "text_column_body",
        parent=style_muted,
        fontSize=9,
        leading=13,
        textColor=TEXT_PRIMARY,
    )

    for col_item in columns[:8]:
        col_name = str(col_item.get("column", "Text Column"))
        sentiment = str(col_item.get("overall_sentiment", "neutral")).lower()
        sentiment_color = GREEN if sentiment == "positive" else (RED if sentiment == "negative" else TEXT_MUTED)

        pos = float(col_item.get("positive_percent", 0) or 0)
        neg = float(col_item.get("negative_percent", 0) or 0)
        neu = float(col_item.get("neutral_percent", 0) or 0)

        dominant_topic = col_item.get("dominant_topic")
        if isinstance(dominant_topic, dict):
            topic_name = str(dominant_topic.get("name", "N/A"))
        else:
            topic_name = str(dominant_topic or "N/A")

        key_phrases = col_item.get("key_phrases", [])
        if isinstance(key_phrases, list):
            phrases = [str(p) for p in key_phrases[:3]]
        else:
            phrases = []

        blocks.append(Paragraph(col_name, heading_style))
        blocks.append(Paragraph(
            f"Sentiment: <font color='{sentiment_color.hexval()}'><b>{sentiment.title()}</b></font>"
            f" (Pos {pos:.1f}% | Neg {neg:.1f}% | Neu {neu:.1f}%)<br/>"
            f"Dominant Topic: <b>{topic_name}</b>",
            body_style,
        ))

        if phrases:
            phrase_cells = [
                Paragraph(f"<font color='{TEXT_PRIMARY.hexval()}'>{phrase}</font>", body_style)
                for phrase in phrases
            ]
            phrase_row = [phrase_cells + [""] * (3 - len(phrase_cells))]
            phrase_table = Table(phrase_row, colWidths=[155, 155, 155])
            phrase_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (len(phrase_cells) - 1, 0), TEAL_LIGHT),
                ("BOX", (0, 0), (len(phrase_cells) - 1, 0), 0.5, BORDER),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            blocks.append(phrase_table)

        blocks.append(Spacer(1, 10))

    if not blocks:
        return Paragraph("No text analysis items available.", style_muted)

    wrapper = Table([[b] for b in blocks], colWidths=[490])
    wrapper.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 1, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return wrapper


def render_report_pdf_bytes(
    executive_summary: str,
    data_quality: Dict[str, Any],
    chart_recommendations: List[Dict[str, Any]],
    dataset_name: str = "Dataset",
    anomalies: List[Dict[str, Any]] = None,
    forecast: Dict[str, Any] = None,
    data_quality_issues: List[Dict[str, Any]] = None,
    text_analysis: Dict[str, Any] = None,
) -> bytes:
    """Render report content as a styled PDF in-memory."""
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    from reportlab.lib.styles import ParagraphStyle

    anomalies = anomalies or []
    buffer = BytesIO()
    today = datetime.date.today().strftime("%B %d, %Y")
    safe_name = (dataset_name or "Dataset").rsplit(".", 1)[0]

    def _on_first_page(canv, doc):
        _draw_header(canv, doc, safe_name, today)
        _draw_footer(canv, doc, safe_name, today)

    def _on_later_pages(canv, doc):
        _draw_footer(canv, doc, safe_name, today)

    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=50,
        rightMargin=50,
        topMargin=60,
        bottomMargin=50,
    )

    story: List[Any] = [Spacer(1, 80)]

    style_normal = ParagraphStyle(
        "normal",
        fontName="Helvetica",
        fontSize=10,
        leading=16,
        textColor=TEXT_PRIMARY,
        spaceAfter=8,
    )
    style_muted = ParagraphStyle(
        "muted",
        fontName="Helvetica",
        fontSize=9,
        leading=14,
        textColor=TEXT_MUTED,
    )

    story.extend(_section_title("Executive Summary"))
    chunks = [p.strip() for p in executive_summary.replace("\n\n", "\n").split("\n") if p.strip()]
    if not chunks:
        chunks = ["No executive summary generated."]
    for paragraph in chunks:
        story.append(Paragraph(paragraph, style_normal))
    story.append(Spacer(1, 16))

    story.extend(_section_title("Data Quality Score"))
    story.append(_build_quality_card(data_quality, style_normal, style_muted))
    story.append(Spacer(1, 16))

    if anomalies:
        story.extend(_section_title("Anomalies Detected"))
        story.append(_build_anomaly_table(anomalies))
        story.append(Spacer(1, 16))

    if chart_recommendations:
        story.extend(_section_title("Chart Recommendations"))
        story.append(_build_chart_cards(chart_recommendations, style_muted))
        story.append(Spacer(1, 16))

    if forecast and forecast.get("timeseries_found", 0) > 0:
        story.extend(_section_title("Predictive Forecast"))
        story.append(_build_forecast_section(forecast.get("forecasts", []), style_normal, style_muted))
        story.append(Spacer(1, 16))

    if text_analysis and text_analysis.get("text_columns_found", 0) > 0:
        story.extend(_section_title("Text & Sentiment Analysis"))
        story.append(_build_text_analysis_section(text_analysis.get("columns", []), style_normal, style_muted))
        story.append(Spacer(1, 16))

    doc.build(story, onFirstPage=_on_first_page, onLaterPages=_on_later_pages)
    buffer.seek(0)
    return buffer.getvalue()


def _wrap_text(text: str, width: int) -> List[str]:
    words = text.split()
    if not words:
        return [""]

    lines: List[str] = []
    current = words[0]
    for word in words[1:]:
        if len(current) + 1 + len(word) <= width:
            current = f"{current} {word}"
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def generate_report(dataframe: pd.DataFrame, statistics: Dict[str, Any], key_manager: Any) -> Dict[str, Any]:
    """Generate a storytelling report payload without exporting a local PDF file."""
    max_cols_raw = (os.getenv("REPORT_MAX_COLUMNS_IN_PROMPT") or "40").strip()
    try:
        max_cols = max(10, int(max_cols_raw))
    except ValueError:
        max_cols = 40

    prompt_columns = dataframe.columns.tolist()[:max_cols]
    prompt_dtypes = {col: str(dtype) for col, dtype in dataframe.dtypes.astype(str).to_dict().items() if col in prompt_columns}

    summary_payload = {
        "rows": int(len(dataframe)),
        "columns": prompt_columns,
        "columns_truncated": len(dataframe.columns) > len(prompt_columns),
        "statistics_keys": list(statistics.keys()),
        "numeric_columns": dataframe.select_dtypes(include=["number"]).columns.tolist()[:max_cols],
        "categorical_columns": dataframe.select_dtypes(exclude=["number"]).columns.tolist()[:max_cols],
    }

    executive_prompt = (
        "Write a 3-paragraph summary of this data for a non-technical CEO. "
        f"Data: {summary_payload}. Cover: overall picture, what needs attention, one surprising finding."
    )

    executive_fallback = (
        "The dataset provides a broad view of current performance across key business dimensions.\n\n"
        "Attention is needed in data consistency and anomaly-heavy fields where variance may impact decisions.\n\n"
        "A notable surprise is the presence of concentrated outliers in otherwise stable distributions."
    )

    def _get_executive_summary() -> str:
        try:
            return key_manager.call_with_retry(
                system_prompt="You are a concise executive data storyteller.",
                user_prompt=executive_prompt,
            )
        except Exception:
            return executive_fallback

    data_quality = _compute_data_quality(dataframe)

    chart_prompt = (
        f"Given columns {prompt_columns} with types {prompt_dtypes}, "
        "recommend 3 chart types. Return JSON array: [{chart_type, x, y, reason}]"
    )
    chart_fallback = [
        {"chart_type": "line", "x": "date", "y": "metric", "reason": "Good for trend tracking."},
        {"chart_type": "bar", "x": "category", "y": "value", "reason": "Compares groups clearly."},
        {"chart_type": "scatter", "x": "feature_1", "y": "feature_2", "reason": "Shows correlation and outliers."},
    ]

    def _get_chart_recommendations() -> List[Dict[str, Any]]:
        try:
            chart_raw = key_manager.call_with_retry(
                system_prompt="You are a BI visualization expert. Return valid JSON only.",
                user_prompt=chart_prompt,
            )
            parsed = _safe_json_loads(chart_raw, chart_fallback)
            if not isinstance(parsed, list):
                return chart_fallback
            return parsed
        except Exception:
            return chart_fallback

    with ThreadPoolExecutor(max_workers=2) as executor:
        summary_future = executor.submit(_get_executive_summary)
        charts_future = executor.submit(_get_chart_recommendations)
        executive_summary = summary_future.result()
        chart_recommendations = charts_future.result()

    return {
        "executive_summary": executive_summary,
        "data_quality": data_quality,
        "chart_recommendations": chart_recommendations,
    }
